version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6
  docker: circleci/docker@2.0.1

executors:
  node:
    docker:
      - image: cimg/node:16.14


x-heroku-app-back: &heroku-app-back

x-heroku-app-front: &heroku-app-front
  app-name: circleci-demo-front
  process-types: web
  working_directory: ~/project/front

jobs:
  install_and_test_back:
    executor: node
    steps:
      - checkout
      - run:
          command: npm i
          working_directory: ~/project/back
      - run:
          command: npm test
          working_directory: ~/project/back

  install_and_test_front:
    executor: node
    steps:
      - checkout
      - run: git submodule update --init
      - run:
          command: yarn install
          working_directory: ~/project/front
      - run:
          command: yarn lint
          working_directory: ~/project/front
      - persist_to_workspace:
          root: ~/project/
          paths:
            - front/

  deploy_docker_back:
    docker:
      - image: cimg/base:2022.02
    steps:
      - heroku/install
      - heroku/check-authentication
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          cd back/ &&
          heroku container:push -a circleci-demo-back web
          heroku container:release -a circleci-demo-back web


  deploy_docker_front:
    docker:
      - image: cimg/base:2022.02
    steps:
      - heroku/install
      - heroku/check-authentication
      - checkout
      - attach_workspace:
          at: ~/project
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          cd back/ &&
          heroku container:push -a circleci-demo-back web
          heroku container:release -a circleci-demo-back web



workflows:
  main:
    jobs:
      - install_and_test_back
      - docker/publish:
          path: back
          context: back
          remote-docker-dlc: true
          lint-dockerfile: true
          image: linkvalue
          tag: ${CIRCLE_SHA1}.back
      - deploy_docker_back:
          requires:
            - install_and_test_back

      - install_and_test_front
      - docker/publish:
          attach-at: ~/project
          path: front
          context: front
          remote-docker-dlc: true
          lint-dockerfile: true
          image: linkvalue
          tag: ${CIRCLE_SHA1}.front
          requires:
            - install_and_test_front
      - deploy_docker_front:
          requires:
            - install_and_test_front
