version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6
  docker: circleci/docker@2.0.1
  irc: circleci/irc@0.2.0

executors:
  node:
    docker:
      - image: cimg/node:16.14

jobs:
  install_and_test_back:
    executor: node
    steps:
      - checkout
      - run:
          command: npm i
          working_directory: ~/project/back
      - run:
          command: npm test
          working_directory: ~/project/back

  install_and_test_front:
    executor: node
    steps:
      - checkout
      - run: git submodule update --init
      - run:
          command: yarn install
          working_directory: ~/project/front
      - run:
          command: yarn lint
          working_directory: ~/project/front
      - persist_to_workspace:
          root: ~/project/
          paths:
            - front/

  deploy_docker_back:
    docker:
      - image: cimg/base:2022.02
    steps:
      - heroku/install
      - heroku/check-authentication
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          cd back/ &&
          heroku container:login &&
          heroku container:push -a circleci-demo-back web
          heroku container:release -a circleci-demo-back web

  deploy_docker_front:
    docker:
      - image: cimg/base:2022.02
    steps:
      - heroku/install
      - heroku/check-authentication
      - checkout
      - run: git submodule update --init
      - run: |
          cd back/ &&
          heroku container:login &&
          heroku container:push -a circleci-demo-back web
          heroku container:release -a circleci-demo-back web

  notify_twitch:
    docker:
      - image: cimg/base:2022.02
    steps:
      - irc/notify:
          nick: fatboi42
          message: >-
            SMOrc I''m a bot SMOrc
            PrideRhino Repo: << pipeline.project.git_url >>
            SeemsGood Successfully built & deployed commit:
            << pipeline.git.revision >>
          server: irc.chat.twitch.tv
          channel: fatboi42

workflows:
  main:
    jobs:
      - install_and_test_back
      - docker/publish:
          path: back
          name: docker_publish_back
          docker-context: back
          lint-dockerfile: true
          image: ruaraidhjc/linkvalue
          tag: ${CIRCLE_SHA1:0:7}.back
          requires:
            - install_and_test_back
      - deploy_docker_back:
          requires:
            - install_and_test_back

      - install_and_test_front
      - docker/publish:
          name: docker_publish_front
          path: front
          after_checkout:
            - run: git submodule update --init
          docker-context: front
          lint-dockerfile: true
          image: ruaraidhjc/linkvalue
          tag: ${CIRCLE_SHA1:0:7}.front
          requires:
            - install_and_test_front
      - deploy_docker_front:
          requires:
            - install_and_test_front

      - notify_twitch:
          requires:
            - docker_publish_back
            - docker_publish_front
            - deploy_docker_back
            - deploy_docker_front
