version: 2.1

parameters:
  run-secret-workflow:
    type: boolean
    default: false

jobs:
  update_secret:
    machine: true
    resource_class: ruaraidhjc/linkvalue
    steps:
      - run: |
          echo "${SECRET_MESSAGE}" | base64 -d > /opt/secrets/secret.txt

workflows:
  secret:
    when: << pipeline.parameters.run-secret-workflow >>
    jobs:
      - update_secret:
          context:
            - runner-secrets
