version: 2.1

executors:
  node:
    docker:
      - image: cimg/node:16.14

jobs:
  install_and_test_back:
    executor: node
    steps:
      - checkout
      - run:
          command: npm i
          working_directory: ~/project/back
      - run:
          command: npm test
          working_directory: ~/project/back

  install_and_test_front:
    executor: node

    steps:
      - checkout
      - run: git submodule update --init
      - run:
          command: yarn install
          working_directory: ~/project/front
      - run:
          command: yarn lint
          working_directory: ~/project/front

  build_and_push_docker_front:
    machine:
      image: ubuntu-2004:202111-02
    working_directory: ~/project/front
    steps:
      - checkout
      - run: docker login -u ruaraidhjc -p ${DOCKER_PASSWORD}
      - run: docker build -t ruaraidhjc/linkvalue:${CIRCLE_SHA1}.front .
      - run: docker push ruaraidhjc/linkvalue:${CIRCLE_SHA1}.front

  build_and_push_docker_back:
    machine:
      image: ubuntu-2004:202111-02
    working_directory: ~/project/back
    steps:
      - checkout
      - run: docker login -u ruaraidhjc -p ${DOCKER_PASSWORD}
      - run: docker build -t ruaraidhjc/linkvalue:${CIRCLE_SHA1}.back .
      - run: docker push ruaraidhjc/linkvalue:${CIRCLE_SHA1}.back

workflows:
  main:
    jobs:
      - install_and_test_back
      - build_and_push_docker_back:
          requires:
            - install_and_test_back
      - install_and_test_front
      - build_and_push_docker_front:
          requires:
            - install_and_test_front
