version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6
  docker: circleci/docker@2.0.1

executors:
  node:
    docker:
      - image: cimg/node:16.14

jobs:
  install_and_test_back:
    executor: node
    steps:
      - checkout
      - run:
          command: npm i
          working_directory: ~/project/back
      - run:
          command: npm test
          working_directory: ~/project/back

  install_and_test_front:
    executor: node
    steps:
      - checkout
      - run: git submodule update --init
      - run:
          command: yarn install
          working_directory: ~/project/front
      - run:
          command: yarn lint
          working_directory: ~/project/front
      - persist_to_workspace:
          root: ~/project/
          paths:
            - front/

  build_and_deploy_docker_front:
    docker:
      - image: cimg/base:2022.02
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
    # - run: git submodule update --init
      - attach_at: ~/project/
      - docker/publish:
          path: front/
          lint-dockerfile: true
          image: linkvalue
          tag: ${CIRCLE_SHA1}.front
      - heroku/push-docker-image:
          working_directory: ~/project/front
          app-name: circleci-demo-front

  build_and_deploy_docker_back:
    machine:
      image: ubuntu-2004:202111-02
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - docker/publish:
          path: back/
          lint-dockerfile: true
          image: linkvalue
          tag: ${CIRCLE_SHA1}.back
      - heroku/push-docker-image:
          working_directory:
          app-name: circleci-demo-back

workflows:
  main:
    jobs:
      - install_and_test_back
      - build_and_push_docker_back:
          requires:
            - install_and_test_back
      - install_and_test_front
      - build_and_push_docker_front:
          requires:
            - install_and_test_front
